container:
  image: node:12

task:
  name: test
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  test_script: yarn test

task:
  name: lint
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  lint_script: yarn lint:fix

task:
  name: build
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn build

# Note: Although this task will take a while, it's the easiest way to check if it runs and to later add
# some checks if the resulting table is 'correct' or not
docker_builder:
  name: Seeder test
  depends_on:
    - lint
    - build
    - test
  start_compose_script: docker run --rm --network host -e "POSTGRES_USER=geocode" -e "POSTGRES_PASSWORD=geocode" -e "POSTGRES_DATABASE=geocode" -p 5432:5432 -d postgres:11
  install_script: docker run --rm --network host -v $PWD/:/app --workdir=/app node:latest sh -c "yarn"
  run_seeder_script: docker run --rm --network host -v $PWD/:/app --workdir=/app node:latest sh -c "yarn run:seeder"
  test_e2e_script: docker run --rm --network host -v $PWD/:/app --workdir=/app node:latest sh -c "yarn test:e2e"
